# coding: utf-8
# @Author: Wang Qingkang

import asyncio
import json
from collections.abc import Callable
from typing import Self

from pymilvus import (
    AnnSearchRequest,
    CollectionSchema,
    DataType,
    Function,
    FunctionType,
    MilvusClient,
    RRFRanker,
)

from agent_layer.config import settings
from agent_layer.embeddings import build_embedding_model
from agent_layer.evidence_schemas import WebsiteEvidence, WebsiteEvidenceDraft


async def _run_sdk_call[**P, T](
    operation: Callable[P, T],
    *args: P.args,
    **kwargs: P.kwargs,
) -> T:
    """Drain a blocking SDK operation before propagating cancellation."""
    worker = asyncio.create_task(asyncio.to_thread(operation, *args, **kwargs))
    cancelled = False
    try:
        while not worker.done():
            try:
                await asyncio.shield(worker)
            except asyncio.CancelledError:
                # Cancelling the await does not stop the SDK's worker thread.
                cancelled = True
        return worker.result()
    finally:
        if cancelled:
            raise asyncio.CancelledError


class EvidencePool:
    """One application-owned writer for a dedicated Milvus evidence collection."""

    def __init__(self) -> None:
        self._client = None
        self._embeddings = build_embedding_model()
        self._write_lock = asyncio.Lock()

    @classmethod
    async def open(cls) -> Self:
        pool = cls()
        try:
            await _run_sdk_call(pool._initialize_collection)
        except BaseException:
            # Connection construction can fail before assigning a client.
            if pool._client is not None:
                await pool.close()
            raise
        return pool

    def _initialize_collection(self) -> None:
        self._client = MilvusClient(
            uri=settings.evidence_milvus_uri,
            token=settings.evidence_milvus_token,
            db_name="tender_qa",
            timeout=settings.evidence_milvus_timeout_seconds,
        )
        exists = self._client.has_collection(
            collection_name="evidences",
            timeout=settings.evidence_milvus_timeout_seconds,
        )
        if not exists:
            index_params = self._client.prepare_index_params()
            index_params.add_index(
                field_name="embedding",
                index_name="embedding",
                index_type="AUTOINDEX",
                metric_type="COSINE",
            )
            index_params.add_index(
                field_name="sparse_embedding",
                index_name="sparse_embedding",
                index_type="SPARSE_INVERTED_INDEX",
                metric_type="BM25",
            )
            self._client.create_collection(
                collection_name="evidences",
                schema=self._collection_schema(),
                index_params=index_params,
                consistency_level="Strong",
                timeout=settings.evidence_milvus_timeout_seconds,
            )
        else:
            self._client.load_collection(
                collection_name="evidences",
                timeout=settings.evidence_milvus_timeout_seconds,
            )

    def _collection_schema(self) -> CollectionSchema:
        schema = MilvusClient.create_schema(
            auto_id=True,
            enable_dynamic_field=False,
            description=(
                "This collection stores evidence generated by LLMs. "
                "Each evidence record belongs to a specific session "
                "and is not shared across sessions."
            ),
        )
        schema.add_field(
            field_name="evidence_id",
            datatype=DataType.VARCHAR,
            max_length=128,
            is_primary=True,
        )
        schema.add_field(
            field_name="session_id",
            datatype=DataType.VARCHAR,
            max_length=128,
        )
        schema.add_field(
            field_name="source_type",
            datatype=DataType.VARCHAR,
            max_length=32,
        )
        schema.add_field(
            field_name="title",
            datatype=DataType.VARCHAR,
            max_length=settings.evidence_title_max_chars * 4,
        )
        schema.add_field(
            field_name="content",
            datatype=DataType.VARCHAR,
            max_length=settings.evidence_content_max_chars * 4,
            enable_analyzer=True,
            analyzer_params={"type": "chinese"},
        )
        schema.add_field(
            field_name="reliability_description",
            datatype=DataType.VARCHAR,
            max_length=settings.evidence_reliability_max_chars * 4,
        )
        schema.add_field(
            field_name="updated_at",
            datatype=DataType.VARCHAR,
            max_length=64,
            nullable=True,
        )
        schema.add_field(
            field_name="url",
            datatype=DataType.VARCHAR,
            max_length=4096,
            nullable=True,
        )
        schema.add_field(
            field_name="embedding",
            datatype=DataType.FLOAT_VECTOR,
            dim=1024,
        )
        schema.add_field(
            field_name="sparse_embedding",
            datatype=DataType.SPARSE_FLOAT_VECTOR,
        )
        schema.add_field(
            field_name="is_removed",
            datatype=DataType.BOOL,
        )
        schema.add_function(
            Function(
                name="content_bm25",
                function_type=FunctionType.BM25,
                input_field_names=["content"],
                output_field_names=["sparse_embedding"],
            )
        )
        return schema

    async def get_evidences(
        self,
        session_id: str,
        question: str,
        limit: int,
    ) -> list[WebsiteEvidence]:
        query_vector = await self._embeddings.aembed_query(question)
        results = await _run_sdk_call(
            self._client.hybrid_search,
            collection_name="evidences",
            reqs=[
                AnnSearchRequest(
                    data=[query_vector],
                    anns_field="embedding",
                    param={"metric_type": "COSINE"},
                    limit=limit,
                    expr=f"session_id == {json.dumps(session_id, ensure_ascii=False)} and is_removed == false",
                ),
                AnnSearchRequest(
                    data=[question],
                    anns_field="sparse_embedding",
                    param={"metric_type": "BM25"},
                    limit=limit,
                    expr=f"session_id == {json.dumps(session_id, ensure_ascii=False)} and is_removed == false",
                ),
            ],
            ranker=RRFRanker(k=60),
            limit=limit,
            output_fields=[*WebsiteEvidenceDraft.model_fields, "session_id"],
            consistency_level="Strong",
            timeout=settings.evidence_milvus_timeout_seconds,
        )
        hits = results[0]
        return [
            WebsiteEvidence(
                **hit["entity"],
                evidence_id=evidence_id,
            )
            for evidence_id, hit in zip(hits.ids, hits)
        ]

    async def get_evidence(
        self,
        session_id: str,
        evidence_id: str,
    ) -> WebsiteEvidence | None:
        record = await self._get_record(
            session_id,
            evidence_id,
            list(WebsiteEvidence.model_fields),
        )
        if record is None:
            return None
        return WebsiteEvidence.model_validate(record)

    async def add_evidence(
        self,
        session_id: str,
        draft: WebsiteEvidenceDraft,
    ) -> WebsiteEvidence:
        record = draft.model_dump(mode="json")
        async with self._write_lock:
            vectors = await self._embeddings.aembed_documents(
                [draft.content]
            )
            vector = vectors[0]
            record["session_id"] = session_id
            record["embedding"] = vector
            record["is_removed"] = False
            result = await _run_sdk_call(
                self._client.insert,
                collection_name="evidences",
                data=[record],
                timeout=settings.evidence_milvus_timeout_seconds,
            )
            return WebsiteEvidence(
                **draft.model_dump(),
                evidence_id=result["ids"][0],
                session_id=session_id,
            )

    async def remove_evidence(
        self,
        session_id: str,
        evidence_id: str,
    ) -> bool:
        async with self._write_lock:
            record = await self._get_record(
                session_id,
                evidence_id,
                ["evidence_id", "is_removed"],
            )
            if record is None or record["is_removed"]:
                return False
            await _run_sdk_call(
                self._client.upsert,
                collection_name="evidences",
                data=[
                    {
                        "evidence_id": evidence_id,
                        "is_removed": True,
                    }
                ],
                partial_update=True,
                timeout=settings.evidence_milvus_timeout_seconds,
            )
            return True

    async def _get_record(
        self,
        session_id: str,
        evidence_id: str,
        output_fields: list[str],
    ) -> dict[str, object] | None:
        records = await _run_sdk_call(
            self._client.query,
            collection_name="evidences",
            filter=(
                f"session_id == {json.dumps(session_id, ensure_ascii=False)} "
                f"and evidence_id == {json.dumps(evidence_id, ensure_ascii=False)}"
            ),
            limit=1,
            output_fields=output_fields,
            consistency_level="Strong",
            timeout=settings.evidence_milvus_timeout_seconds,
        )
        if not records:
            return None
        return records[0]

    async def close(self) -> None:
        async with self._write_lock:
            await _run_sdk_call(self._client.close)